apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ma-frontend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ma-frontend
    spec:
      containers:
      - name: ma-frontend
        image: eu.gcr.io/sixth-spot-273818/IMAGE:TAG
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m              
