on: push
name: Sonarqube Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@master
    - name: Setup sonar scanner
      uses: warchant/setup-sonar-scanner@v1
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'  
    - name: Setup watchers
      run: |
       sudo gedit /etc/sysctl.conf
       fs.inotify.max_user_watches=524288
       sudo sysctl -p     
    - name: Setup typescript
      run: npm install 
    - name: Run tests
      run: npm test 
    - name: SonarQube Scan
      run: sonar-scanner -Dsonar.projectKey=frontend -Dsonar.sources=. -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
